//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com0com.Redirector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com0com.Redirector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [References]
        ///setupc=C:\Program Files (x86)\com0com\setupc.exe
        ///setupg=C:\Program Files (x86)\com0com\setupg.exe
        ///com2tcp-rfc2217=C:\Program Files (x86)\com0com\hub4com\com2tcp-rfc2217.bat
        ///com2tcp=C:\Program Files (x86)\com0com\hub4com\com2tcp.exe
        ///hub4com=C:\Program Files (x86)\com0com\hub4com\hub4com.exe
        ///
        ///[0]
        ///AutoStart=False
        ///StopWhenPortAClosed=False
        ///CommsMode=RFC2217
        ///RemoteIP=192.168.1.1
        ///RemotePort=7001
        ///LocalPort=8001
        ///Options=--reconnect 15
        ///
        ///[1]
        ///AutoStart=False
        ///StopWhenPortAClosed=False
        ///Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultIni {
            get {
                return ResourceManager.GetString("DefaultIni", resourceCulture);
            }
        }
    }
}
